version: "3"
services:
  ghost:
    # image: ghost:3-alpine
    build: .
    # dockerfile: Dockerfile

    container_name: softup-blog
    restart: always
    ports:
      - 3001:2368
    env_file:
      - web-variables.env
    # volumes:
    #   - ./blog/content/themes/casper:/var/lib/ghost/content/themes/casper
  db:
    image: mysql:5.7
    container_name: softup-blog-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
