version: '3'
services:
  ghost:
    image: 485652621123.dkr.ecr.eu-central-1.amazonaws.com/ghost-server:latest
    container_name: softup-blog
    restart: always
    ports:
      - 80:2368
    env_file:
      - .env
