version: '3'
services:
  ghost:
    image: ghost:latest
    container_name: softup-blog
    ports:
      - 443:2368
    environment: 
      database__client: ${database__client}
      database__connection__host: ${database__connection__host}
      database__connection__user: ${database__connection__user}
      database__connection__password: ${database__connection__password}
      database__connection__database: ${database__connection__database}
      NODE_ENV: ${NODE_ENV}
      url: ${url}